runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app    # refers to var "app" (a WSGI application) in "main.py"

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe                                                              
  version: latest 

builtins:
- remote_api: on

env_variables:
  COMIC_KEY: "e3a28e9f8db9880699b8751b9193af2aed2882a6"